source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXTencentOpenAPI_Example', :exclusive => true do
  pod 'BXTencentOpenAPI', :path => '../'
end

target 'BXTencentOpenAPI_Tests', :exclusive => true do
  pod 'BXTencentOpenAPI', :path => '../'

  
end
